# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComputeViewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 733)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/Application.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.CentralWidgetLayout = QtWidgets.QVBoxLayout(self.CentralWidget)
        self.CentralWidgetLayout.setObjectName("CentralWidgetLayout")
        self.RightRegionLayout = QtWidgets.QGridLayout()
        self.RightRegionLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RightRegionLayout.setObjectName("RightRegionLayout")
        self.RightRegionGroup = QtWidgets.QGroupBox(self.CentralWidget)
        self.RightRegionGroup.setObjectName("RightRegionGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.RightRegionGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.DispatchButtonLayout = QtWidgets.QGridLayout()
        self.DispatchButtonLayout.setObjectName("DispatchButtonLayout")
        self.DispatchButton = QtWidgets.QPushButton(self.RightRegionGroup)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DispatchButton.setFont(font)
        self.DispatchButton.setObjectName("DispatchButton")
        self.DispatchButtonLayout.addWidget(self.DispatchButton, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.DispatchButtonLayout, 2, 0, 1, 2)
        self.ImageSettingsLayout = QtWidgets.QGridLayout()
        self.ImageSettingsLayout.setObjectName("ImageSettingsLayout")
        self.ImageSettingsGroupBox = QtWidgets.QGroupBox(self.RightRegionGroup)
        self.ImageSettingsGroupBox.setObjectName("ImageSettingsGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ImageSettingsGroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ImageDimensionsLayout = QtWidgets.QGridLayout()
        self.ImageDimensionsLayout.setObjectName("ImageDimensionsLayout")
        self.ImageDimensionsGroupBox = QtWidgets.QGroupBox(self.ImageSettingsGroupBox)
        self.ImageDimensionsGroupBox.setObjectName("ImageDimensionsGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ImageDimensionsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ImageWidthLabel = QtWidgets.QLabel(self.ImageDimensionsGroupBox)
        self.ImageWidthLabel.setObjectName("ImageWidthLabel")
        self.gridLayout_2.addWidget(self.ImageWidthLabel, 0, 0, 1, 1)
        self.ImageWidthLineEdit = QtWidgets.QLineEdit(self.ImageDimensionsGroupBox)
        self.ImageWidthLineEdit.setObjectName("ImageWidthLineEdit")
        self.gridLayout_2.addWidget(self.ImageWidthLineEdit, 0, 1, 1, 1)
        self.ImageHeightLabel = QtWidgets.QLabel(self.ImageDimensionsGroupBox)
        self.ImageHeightLabel.setObjectName("ImageHeightLabel")
        self.gridLayout_2.addWidget(self.ImageHeightLabel, 1, 0, 1, 1)
        self.ImageHeightLineEdit = QtWidgets.QLineEdit(self.ImageDimensionsGroupBox)
        self.ImageHeightLineEdit.setObjectName("ImageHeightLineEdit")
        self.gridLayout_2.addWidget(self.ImageHeightLineEdit, 1, 1, 1, 1)
        self.ImageDimensionsLayout.addWidget(self.ImageDimensionsGroupBox, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.ImageDimensionsLayout, 0, 0, 1, 1)
        self.ImageSettingsLayout.addWidget(self.ImageSettingsGroupBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.ImageSettingsLayout, 1, 0, 1, 1)
        self.PreviewImageLayout = QtWidgets.QGridLayout()
        self.PreviewImageLayout.setObjectName("PreviewImageLayout")
        self.PreviewImageLabel = QtWidgets.QLabel(self.RightRegionGroup)
        self.PreviewImageLabel.setStyleSheet("background-color: palette(dark)")
        self.PreviewImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.PreviewImageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PreviewImageLabel.setLineWidth(2)
        self.PreviewImageLabel.setText("")
        self.PreviewImageLabel.setObjectName("PreviewImageLabel")
        self.PreviewImageLayout.addWidget(self.PreviewImageLabel, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.PreviewImageLayout, 0, 0, 1, 2)
        self.DispatchSettingsLayout = QtWidgets.QGridLayout()
        self.DispatchSettingsLayout.setObjectName("DispatchSettingsLayout")
        self.DispatchSettingsBox = QtWidgets.QGroupBox(self.RightRegionGroup)
        self.DispatchSettingsBox.setObjectName("DispatchSettingsBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.DispatchSettingsBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.DispatchDimensionsLayout = QtWidgets.QGridLayout()
        self.DispatchDimensionsLayout.setObjectName("DispatchDimensionsLayout")
        self.DispatchDimensionsGroupBox = QtWidgets.QGroupBox(self.DispatchSettingsBox)
        self.DispatchDimensionsGroupBox.setObjectName("DispatchDimensionsGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.DispatchDimensionsGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.DispatchXLabel = QtWidgets.QLabel(self.DispatchDimensionsGroupBox)
        self.DispatchXLabel.setObjectName("DispatchXLabel")
        self.gridLayout_5.addWidget(self.DispatchXLabel, 0, 0, 1, 1)
        self.DispatchYLineEdit = QtWidgets.QLineEdit(self.DispatchDimensionsGroupBox)
        self.DispatchYLineEdit.setObjectName("DispatchYLineEdit")
        self.gridLayout_5.addWidget(self.DispatchYLineEdit, 1, 1, 1, 1)
        self.DispatchYLabel = QtWidgets.QLabel(self.DispatchDimensionsGroupBox)
        self.DispatchYLabel.setObjectName("DispatchYLabel")
        self.gridLayout_5.addWidget(self.DispatchYLabel, 1, 0, 1, 1)
        self.DispatchXLineEdit = QtWidgets.QLineEdit(self.DispatchDimensionsGroupBox)
        self.DispatchXLineEdit.setObjectName("DispatchXLineEdit")
        self.gridLayout_5.addWidget(self.DispatchXLineEdit, 0, 1, 1, 1)
        self.DispatchZLineEdit = QtWidgets.QLineEdit(self.DispatchDimensionsGroupBox)
        self.DispatchZLineEdit.setObjectName("DispatchZLineEdit")
        self.gridLayout_5.addWidget(self.DispatchZLineEdit, 2, 1, 1, 1)
        self.DispatchZLabel = QtWidgets.QLabel(self.DispatchDimensionsGroupBox)
        self.DispatchZLabel.setObjectName("DispatchZLabel")
        self.gridLayout_5.addWidget(self.DispatchZLabel, 2, 0, 1, 1)
        self.DispatchDimensionsLayout.addWidget(self.DispatchDimensionsGroupBox, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.DispatchDimensionsLayout, 0, 0, 1, 1)
        self.DispatchSettingsLayout.addWidget(self.DispatchSettingsBox, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.DispatchSettingsLayout, 1, 1, 1, 1)
        self.RightRegionLayout.addWidget(self.RightRegionGroup, 0, 0, 1, 1)
        self.CentralWidgetLayout.addLayout(self.RightRegionLayout)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 485, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_ComputeViewer = QtWidgets.QAction(MainWindow)
        self.actionAbout_ComputeViewer.setObjectName("actionAbout_ComputeViewer")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_ComputeViewer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ComputeViewer 1.0"))
        self.RightRegionGroup.setTitle(_translate("MainWindow", "Preview"))
        self.DispatchButton.setText(_translate("MainWindow", "Dispatch"))
        self.ImageSettingsGroupBox.setTitle(_translate("MainWindow", "Image Settings"))
        self.ImageDimensionsGroupBox.setTitle(_translate("MainWindow", "Dimensions"))
        self.ImageWidthLabel.setText(_translate("MainWindow", "Width"))
        self.ImageWidthLineEdit.setText(_translate("MainWindow", "0"))
        self.ImageHeightLabel.setText(_translate("MainWindow", "Height"))
        self.ImageHeightLineEdit.setText(_translate("MainWindow", "0"))
        self.DispatchSettingsBox.setTitle(_translate("MainWindow", "Dispatch Settings"))
        self.DispatchDimensionsGroupBox.setTitle(_translate("MainWindow", "Dimensions"))
        self.DispatchXLabel.setText(_translate("MainWindow", "X"))
        self.DispatchYLineEdit.setText(_translate("MainWindow", "0"))
        self.DispatchYLabel.setText(_translate("MainWindow", "Y"))
        self.DispatchXLineEdit.setText(_translate("MainWindow", "0"))
        self.DispatchZLineEdit.setText(_translate("MainWindow", "1"))
        self.DispatchZLabel.setText(_translate("MainWindow", "Z"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New Shader"))
        self.actionLoad.setText(_translate("MainWindow", "Load Shader"))
        self.actionSave.setText(_translate("MainWindow", "Save Shader"))
        self.actionSave_As.setText(_translate("MainWindow", "Save Shader As"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout_ComputeViewer.setText(_translate("MainWindow", "About ComputeViewer"))
